<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>meeting-room-api-development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abp.MeetingRoom.Bll.Common\Abp.MeetingRoom.Bll.Common.csproj" />
    <ProjectReference Include="..\Abp.MeetingRoom.Dal.SqlRepositories\Abp.MeetingRoom.Dal.SqlRepositories.csproj" />
    <ProjectReference Include="..\Abp.MeetingRoom.Bll\Abp.MeetingRoom.Bll.csproj" />
  </ItemGroup>
</Project>
